export const PUBLIC_APPWRITE_ENDPOINT = "__APPWRITE_ENDPOINT__";
export const PUBLIC_APPWRITE_PROJECT_ID = "__APPWRITE_PROJECT_ID__";
export const PUBLIC_APPWRITE_DATABASE_ID = "__APPWRITE_DATABASE_ID__";
export const PUBLIC_APPWRITE_TABLE_ID = "__APPWRITE_TABLE_ID__";
