services:
  question-bank:
    image: yaqba:2.1.1
    container_name: yaqba
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
    ports:
      - "8880:8080"
    cap_drop:
      - ALL
    restart: unless-stopped
