services:
  question-bank:
    image: yaqba:2.0.4
    container_name: yaqba
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
    ports:
      - "8880:8080"
    environment:
      - APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT}
      - APPWRITE_PROJECT_NAME=${APPWRITE_PROJECT_NAME}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID}
      - APPWRITE_DATABASE_ID=${APPWRITE_DATABASE_ID}
      - APPWRITE_TABLE_ID=${APPWRITE_TABLE_ID}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: unless-stopped
